version: "3.8"

services:

  accounts:
    image: brittodk/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - brittodk-network

  loans:
    image: brittodk/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - brittodk-network

  cards:
    image: brittodk/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - brittodk-network

networks:
  brittodk-network: